export const CHARACTER_BASE_URL = 'https://kss-lp.vercel.app/characters/';
export const SUZURI_SHOP_URL = 'https://suzuri.jp/hoshimori-official';

export const CHARACTER_MAP: Record<string, { name: string, file: string, suzuriDesignId?: string }> = {
  '1_甲': { name: 'アイス', file: '1_kou', suzuriDesignId: '19967270' },
  '1_乙': { name: 'タンブラー', file: '1_otsu', suzuriDesignId: '19967358' },
  '1_丙': { name: 'ピクス', file: '1_hei', suzuriDesignId: '19965598' },
  '1_丁': { name: 'カーク', file: '1_tei', suzuriDesignId: '19967447' },
  '1_戊': { name: 'ゴードン', file: '1_bo', suzuriDesignId: '19967068' },
  '1_己': { name: 'ポレフ', file: '1_ki', suzuriDesignId: '19967182' },
  '1_庚': { name: 'リンガー', file: '1_kou2', suzuriDesignId: '19967321' },
  '1_辛': { name: 'オルガ', file: '1_shin', suzuriDesignId: '19967386' },
  '1_壬': { name: 'アデュー', file: '1_jin', suzuriDesignId: '19967396' },
  '1_癸': { name: 'ウォルター', file: '1_ki2', suzuriDesignId: '19967122' },
  '2_甲': { name: 'ホーリー', file: '2_kou', suzuriDesignId: '19968998' },
  '2_乙': { name: 'エマ', file: '2_otsu', suzuriDesignId: '19965670' },
  '2_丙': { name: 'プーミー', file: '2_hei', suzuriDesignId: '19969034' },
  '2_丁': { name: 'コトン', file: '2_tei', suzuriDesignId: '19969073' },
  '2_戊': { name: 'タンタン', file: '2_bo', suzuriDesignId: '19969097' },
  '2_己': { name: 'ゴルトン', file: '2_ki', suzuriDesignId: '19969138' },
  '2_庚': { name: 'ダルリ', file: '2_kou2', suzuriDesignId: '19969228' },
  '2_辛': { name: 'ポポ', file: '2_shin', suzuriDesignId: '19969281' },
  '2_壬': { name: 'イース', file: '2_jin', suzuriDesignId: '19969343' },
  '2_癸': { name: 'アリアナ', file: '2_ki2', suzuriDesignId: '19969413' },
  '3_甲': { name: 'テント', file: '3_kou' },
  '3_乙': { name: 'オリー', file: '3_otsu' },
  '3_丙': { name: 'レミー', file: '3_hei' },
  '3_丁': { name: 'ジャスパー', file: '3_tei' },
  '3_戊': { name: 'ムーチョ', file: '3_bo' },
  '3_己': { name: 'シケダ', file: '3_ki' },
  '3_庚': { name: 'マルファン', file: '3_kou2' },
  '3_辛': { name: 'リンク', file: '3_shin' },
  '3_壬': { name: 'バン', file: '3_jin' },
  '3_癸': { name: 'ユルグ', file: '3_ki2' },
  '4_甲': { name: 'ペイジー', file: '4_kou' },
  '4_乙': { name: 'ナーム', file: '4_otsu' },
  '4_丙': { name: 'サーシャ', file: '4_hei' },
  '4_丁': { name: 'アントニー', file: '4_tei' },
  '4_戊': { name: 'クラウディア', file: '4_bo' },
  '4_己': { name: 'ピット', file: '4_ki' },
  '4_庚': { name: 'ジャイロ', file: '4_kou2' },
  '4_辛': { name: 'ペスカ', file: '4_shin' },
  '4_壬': { name: 'シーグル', file: '4_jin' },
  '4_癸': { name: 'カカオ', file: '4_ki2' },
  '5_甲': { name: 'ファンタ', file: '5_kou' },
  '5_乙': { name: 'ヴァーナ', file: '5_otsu' },
  '5_丙': { name: 'ソラリ', file: '5_hei' },
  '5_丁': { name: 'シスコ', file: '5_tei' },
  '5_戊': { name: 'シャーロット', file: '5_bo' },
  '5_己': { name: 'ロジャー', file: '5_ki' },
  '5_庚': { name: 'ドミノ', file: '5_kou2' },
  '5_辛': { name: 'チップス', file: '5_shin' },
  '5_壬': { name: 'ペトン', file: '5_jin' },
  '5_癸': { name: 'アーナンダ', file: '5_ki2' },
  '6_甲': { name: 'モーリス', file: '6_kou' },
  '6_乙': { name: 'カーラ', file: '6_otsu' },
  '6_丙': { name: 'アデル', file: '6_hei' },
  '6_丁': { name: 'メルシー', file: '6_tei' },
  '6_戊': { name: 'ドンナ', file: '6_bo' },
  '6_己': { name: 'エイド', file: '6_ki' },
  '6_庚': { name: 'アイマン', file: '6_kou2' },
  '6_辛': { name: 'ベロア', file: '6_shin' },
  '6_壬': { name: 'ワッチ', file: '6_jin' },
  '6_癸': { name: 'ダンテ', file: '6_ki2' },
  '7_甲': { name: 'パット', file: '7_kou' },
  '7_乙': { name: 'チャーリー', file: '7_otsu' },
  '7_丙': { name: 'ミラ', file: '7_hei' },
  '7_丁': { name: 'ステファニー', file: '7_tei' },
  '7_戊': { name: 'クッキー', file: '7_bo' },
  '7_己': { name: 'グミー', file: '7_ki' },
  '7_庚': { name: 'リック', file: '7_kou2' },
  '7_辛': { name: 'マーガレット', file: '7_shin' },
  '7_壬': { name: 'ペインター', file: '7_jin' },
  '7_癸': { name: 'イーリア', file: '7_ki2' },
  '8_甲': { name: 'ボタゴン', file: '8_kou' },
  '8_乙': { name: 'ミスト', file: '8_otsu' },
  '8_丙': { name: 'ブランドン', file: '8_hei' },
  '8_丁': { name: 'グーニー', file: '8_tei' },
  '8_戊': { name: 'フラッフィー', file: '8_bo' },
  '8_己': { name: 'ウォル', file: '8_ki' },
  '8_庚': { name: 'グレース', file: '8_kou2' },
  '8_辛': { name: 'メイソン', file: '8_shin' },
  '8_壬': { name: 'タジー', file: '8_jin' },
  '8_癸': { name: 'ポコ', file: '8_ki2' },
  '9_甲': { name: 'ヴェロニカ', file: '9_kou' },
  '9_乙': { name: 'エレフ', file: '9_otsu' },
  '9_丙': { name: 'フィオナ', file: '9_hei' },
  '9_丁': { name: 'ニコール', file: '9_tei' },
  '9_戊': { name: 'バルモア', file: '9_bo' },
  '9_己': { name: 'シーザー', file: '9_ki' },
  '9_庚': { name: 'ピッカ', file: '9_kou2' },
  '9_辛': { name: 'ステラ', file: '9_shin' },
  '9_壬': { name: 'ミンク', file: '9_jin' },
  '9_癸': { name: 'ウーパ', file: '9_ki2', suzuriDesignId: '19967252' },
};

export function getCharacterImageUrl(id: string): string {
  const char = CHARACTER_MAP[id];
  if (char) {
    return `${CHARACTER_BASE_URL}${char.file}.png`;
  }
  return '/hero.png'; // Fallback
}

export function getSuzuriDesignUrl(id: string): string {
  const char = CHARACTER_MAP[id];
  if (char?.suzuriDesignId) {
    return `${SUZURI_SHOP_URL}/designs/${char.suzuriDesignId}`;
  }
  // 専用デザインがない場合はショップトップへ誘導
  return SUZURI_SHOP_URL;
}

export const CHARACTER_NAMES: Record<string, Record<string, string>> = {
  '1_甲': {
    ja: 'アイス',
    en: 'Ice',
    zh: '冰淇淋',
    ko: '아이스',
    es: 'Hielo',
    fr: 'Glace',
    de: 'Eis',
    ru: 'Ледяной',
    pt: 'Sorvete',
  },
  '1_乙': {
    ja: 'タンブラー',
    en: 'Tumbler',
    zh: '水瓶花',
    ko: '탐블러',
    es: 'Tazón',
    fr: 'Trembleur',
    de: 'Tumbler',
    ru: 'Тамблер',
    pt: 'Tampinha',
  },
  '1_丙': {
    ja: 'ピクス',
    en: 'Pix',
    zh: '皮克斯',
    ko: '픽스',
    es: 'Pixus',
    fr: 'Pix',
    de: 'Piks',
    ru: 'Пикс',
    pt: 'Pikus',
  },
  '1_丁': {
    ja: 'カーク',
    en: 'Kirk',
    zh: '卡克',
    ko: '카크',
    es: 'Kirk',
    fr: 'Kirk',
    de: 'Kirk',
    ru: 'Карк',
    pt: 'Kirk',
  },
  '1_戊': {
    ja: 'ゴードン',
    en: 'Gordon',
    zh: '戈登',
    ko: '고든',
    es: 'Gordon',
    fr: 'Gordon',
    de: 'Gordon',
    ru: 'Гордон',
    pt: 'Gordon',
  },
  '1_己': {
    ja: 'ポレフ',
    en: 'Porefu',
    zh: '波雷夫',
    ko: '폴레프',
    es: 'Porefu',
    fr: 'Poref',
    de: 'Polef',
    ru: 'Полеф',
    pt: 'Poléf',
  },
  '1_庚': {
    ja: 'リンガー',
    en: 'Ringer',
    zh: '琳嘉',
    ko: '링거',
    es: 'Ringer',
    fr: 'Ringer',
    de: 'Ringer',
    ru: 'Лингер',
    pt: 'Linger',
  },
  '1_辛': {
    ja: 'オルガ',
    en: 'Olga',
    zh: '奧爾嘉',
    ko: '올가',
    es: 'Olga',
    fr: 'Orga',
    de: 'Olga',
    ru: 'Ольга',
    pt: 'Olga',
  },
  '1_壬': {
    ja: 'アデュー',
    en: 'Adew',
    zh: '阿德優',
    ko: '아데유',
    es: 'Adieu',
    fr: 'Adieu',
    de: 'Adieu',
    ru: 'Адею',
    pt: 'Adeu',
  },
  '1_癸': {
    ja: 'ウォルター',
    en: 'Walter',
    zh: '沃爾特',
    ko: '월터',
    es: 'Walter',
    fr: 'Walter',
    de: 'Walter',
    ru: 'Уолтер',
    pt: 'Walter',
  },
  '2_甲': {
    ja: 'ホーリー',
    en: 'Holy',
    zh: '霍莉',
    ko: '홀리',
    es: 'Holy',
    fr: 'Holy',
    de: 'Holly',
    ru: 'Холи',
    pt: 'Holly',
  },
  '2_乙': {
    ja: 'エマ',
    en: 'Emma',
    zh: '艾瑪',
    ko: '엠마',
    es: 'Emma',
    fr: 'Emma',
    de: 'Emma',
    ru: 'Эмма',
    pt: 'Emma',
  },
  '2_丙': {
    ja: 'プーミー',
    en: 'Pumi',
    zh: '普美',
    ko: '푸미',
    es: 'Poomi',
    fr: 'Poomi',
    de: 'Pumi',
    ru: 'Пуми',
    pt: 'Pumi',
  },
  '2_丁': {
    ja: 'コトン',
    en: 'Koton',
    zh: '科頓',
    ko: '코톤',
    es: 'Koton',
    fr: 'Koton',
    de: 'Koton',
    ru: 'Котон',
    pt: 'Koton',
  },
  '2_戊': {
    ja: 'タンタン',
    en: 'Tantan',
    zh: '湯湯',
    ko: '탄탄',
    es: 'TanTan',
    fr: 'Tantan',
    de: 'Tantan',
    ru: 'ТанТан',
    pt: 'Tantan',
  },
  '2_己': {
    ja: 'ゴルトン',
    en: 'Gorton',
    zh: '戈爾頓',
    ko: '골턴',
    es: 'Goltón',
    fr: 'Goulton',
    de: 'Golton',
    ru: 'Голтон',
    pt: 'Gortan',
  },
  '2_庚': {
    ja: 'ダルリ',
    en: 'Dalri',
    zh: '達爾里',
    ko: '달리',
    es: 'Dalri',
    fr: 'Dalri',
    de: 'Daluri',
    ru: 'Далури',
    pt: 'Dalri',
  },
  '2_辛': {
    ja: 'ポポ',
    en: 'Popo',
    zh: '波波',
    ko: '포포',
    es: 'Popo',
    fr: 'Popo',
    de: 'Popo',
    ru: 'Попо',
    pt: 'Popo',
  },
  '2_壬': {
    ja: 'イース',
    en: 'Eas',
    zh: '伊斯',
    ko: '이스',
    es: 'Ith',
    fr: 'Eas',
    de: 'Eis',
    ru: 'Иис',
    pt: 'Ise',
  },
  '2_癸': {
    ja: 'アリアナ',
    en: 'Ariana',
    zh: '阿莉安娜',
    ko: '아리아나',
    es: 'Ariana',
    fr: 'Ariana',
    de: 'Ariana',
    ru: 'Ариана',
    pt: 'Ariana',
  },
  '3_甲': {
    ja: 'テント',
    en: 'Tent',
    zh: '帳篷',
    ko: '텐트',
    es: 'Tienda',
    fr: 'Tente',
    de: 'Zelt',
    ru: 'Тэнт',
    pt: 'Tenda',
  },
  '3_乙': {
    ja: 'オリー',
    en: 'Ollie',
    zh: '奧莉',
    ko: '올리',
    es: 'Olive',
    fr: 'Ollie',
    de: 'Olli',
    ru: 'Олли',
    pt: 'Oli',
  },
  '3_丙': {
    ja: 'レミー',
    en: 'Remy',
    zh: '雷米',
    ko: '레미',
    es: 'Remy',
    fr: 'Rémi',
    de: 'Remy',
    ru: 'Реми',
    pt: 'Remy',
  },
  '3_丁': {
    ja: 'ジャスパー',
    en: 'Jasper',
    zh: '賈斯珀',
    ko: '자스퍼',
    es: 'Jasper',
    fr: 'Jasper',
    de: 'Jasper',
    ru: 'Джаспер',
    pt: 'Jasper',
  },
  '3_戊': {
    ja: 'ムーチョ',
    en: 'Mucho',
    zh: '穆丘',
    ko: '무쵸',
    es: 'Mucho',
    fr: 'Mucho',
    de: 'Muño',
    ru: 'Мучо',
    pt: 'Mucho',
  },
  '3_己': {
    ja: 'シケダ',
    en: 'Shikeda',
    zh: 'シケダ',
    ko: '시케다',
    es: 'Shikeda',
    fr: 'Shikeda',
    de: 'Shikeda',
    ru: 'Шикэда',
    pt: 'Shikeda',
  },
  '3_庚': {
    ja: 'マルファン',
    en: 'Marfan',
    zh: '馬爾凡',
    ko: '말판',
    es: 'Marufan',
    fr: 'Marfan',
    de: 'Marfan',
    ru: 'Марфан',
    pt: 'Marufan',
  },
  '3_辛': {
    ja: 'リンク',
    en: 'Link',
    zh: '連結',
    ko: '링크',
    es: 'Link',
    fr: 'Link',
    de: 'Link',
    ru: 'Линк',
    pt: 'Link',
  },
  '3_壬': {
    ja: 'バン',
    en: 'Ban',
    zh: '班',
    ko: '반',
    es: 'Ban',
    fr: 'Ban',
    de: 'Ban',
    ru: 'Бан',
    pt: 'Ban',
  },
  '3_癸': {
    ja: 'ユルグ',
    en: 'Yurugu',
    zh: '尤爾格',
    ko: '유르그',
    es: 'Yurg',
    fr: 'Yurugu',
    de: 'Yurugu',
    ru: 'Юлг',
    pt: 'Yurugu',
  },
  '4_甲': {
    ja: 'ペイジー',
    en: 'Paige',
    zh: '佩吉',
    ko: '페이지',
    es: 'Peijí',
    fr: 'Peiji',
    de: 'Peidži',
    ru: 'Пейджи',
    pt: 'Peijy',
  },
  '4_乙': {
    ja: 'ナーム',
    en: 'Naam',
    zh: '娜姆',
    ko: '나움',
    es: 'Naum',
    fr: 'Narm',
    de: 'Naam',
    ru: 'Нам',
    pt: 'Naamu',
  },
  '4_丙': {
    ja: 'サーシャ',
    en: 'Sasha',
    zh: '薩夏',
    ko: '사샤',
    es: 'Sasha',
    fr: 'Sasha',
    de: 'Sasha',
    ru: 'Саша',
    pt: 'Sasha',
  },
  '4_丁': {
    ja: 'アントニー',
    en: 'Anthony',
    zh: '安東尼',
    ko: '안토니',
    es: 'Antonio',
    fr: 'Antony',
    de: 'Anthony',
    ru: 'Антони',
    pt: 'Antônio',
  },
  '4_戊': {
    ja: 'クラウディア',
    en: 'Claudia',
    zh: '克勞迪亞',
    ko: '클라우디아',
    es: 'Claudia',
    fr: 'Claudia',
    de: 'Claudia',
    ru: 'Клаудия',
    pt: 'Cláudia',
  },
  '4_己': {
    ja: 'ピット',
    en: 'Pitt',
    zh: '皮特',
    ko: '핏',
    es: 'Pitt',
    fr: 'Pitt',
    de: 'Pitt',
    ru: 'Питт',
    pt: 'Pitt',
  },
  '4_庚': {
    ja: 'ジャイロ',
    en: 'Gyro',
    zh: '捷盞',
    ko: '자이로',
    es: 'Gyro',
    fr: 'Gyro',
    de: 'Gyro',
    ru: 'Джайро',
    pt: 'Gairo',
  },
  '4_辛': {
    ja: 'ペスカ',
    en: 'Pesca',
    zh: '佩斯卡',
    ko: '페스카',
    es: 'Pesca',
    fr: 'Pescara',
    de: 'Peska',
    ru: 'Песка',
    pt: 'Pesca',
  },
  '4_壬': {
    ja: 'シーグル',
    en: 'Seagull',
    zh: '希格爾',
    ko: '시그룰',
    es: 'Shigrul',
    fr: 'Cigale',
    de: 'Seegreif',
    ru: 'Сигул',
    pt: 'Shiguru',
  },
  '4_癸': {
    ja: 'カカオ',
    en: 'Cacao',
    zh: '可可',
    ko: '카카오',
    es: 'Cacao',
    fr: 'Cacao',
    de: 'Kakao',
    ru: 'Какао',
    pt: 'Cacau',
  },
  '5_甲': {
    ja: 'ファンタ',
    en: 'Fanta',
    zh: '法蘭達',
    ko: '판타',
    es: 'Fanta',
    fr: 'Fanta',
    de: 'Fant',
    ru: 'Фанта',
    pt: 'Fanta',
  },
  '5_乙': {
    ja: 'ヴァーナ',
    en: 'Verna',
    zh: '瓦娜',
    ko: '바르나',
    es: 'Verna',
    fr: 'Varnah',
    de: 'Vana',
    ru: 'Варна',
    pt: 'Varna',
  },
  '5_丙': {
    ja: 'ソラリ',
    en: 'Solaris',
    zh: '索拉里',
    ko: '소라리',
    es: 'Solaris',
    fr: 'Solaris',
    de: 'Sorari',
    ru: 'Солари',
    pt: 'Solaris',
  },
  '5_丁': {
    ja: 'シスコ',
    en: 'Cisco',
    zh: '希斯科',
    ko: '시스코',
    es: 'Sisco',
    fr: 'Cisco',
    de: 'Cisco',
    ru: 'Сиско',
    pt: 'Cisco',
  },
  '5_戊': {
    ja: 'シャーロット',
    en: 'Charlotte',
    zh: '夏洛特',
    ko: '샬롯',
    es: 'Charlotte',
    fr: 'Charlotte',
    de: 'Charlotte',
    ru: 'Шарлотта',
    pt: 'Charlotte',
  },
  '5_己': {
    ja: 'ロジャー',
    en: 'Roger',
    zh: '羅傑',
    ko: '로저',
    es: 'Roger',
    fr: 'Roger',
    de: 'Roger',
    ru: 'Роджер',
    pt: 'Roger',
  },
  '5_庚': {
    ja: 'ドミノ',
    en: 'Domino',
    zh: '多米諾',
    ko: '도미노',
    es: 'Domino',
    fr: 'Domino',
    de: 'Domino',
    ru: 'Домино',
    pt: 'Domino',
  },
  '5_辛': {
    ja: 'チップス',
    en: 'Chips',
    zh: '薯條',
    ko: '칩스',
    es: 'Chips',
    fr: 'Chips',
    de: 'Chips',
    ru: 'Чипсы',
    pt: 'Chips',
  },
  '5_壬': {
    ja: 'ペトン',
    en: 'Peton',
    zh: '佩頓',
    ko: '페톤',
    es: 'Petón',
    fr: 'Péton',
    de: 'Peton',
    ru: 'Петон',
    pt: 'Peton',
  },
  '5_癸': {
    ja: 'アーナンダ',
    en: 'Ananda',
    zh: '阿那達',
    ko: '아난다',
    es: 'Ananda',
    fr: 'Ānanda',
    de: 'Ananda',
    ru: 'Ананда',
    pt: 'Ananda',
  },
  '6_甲': {
    ja: 'モーリス',
    en: 'Maurice',
    zh: '莫里斯',
    ko: '모리스',
    es: 'Maurice',
    fr: 'Maurice',
    de: 'Maurice',
    ru: 'Морис',
    pt: 'Maurice',
  },
  '6_乙': {
    ja: 'カーラ',
    en: 'Kara',
    zh: '卡拉',
    ko: '카라',
    es: 'Kara',
    fr: 'Kara',
    de: 'Kaara',
    ru: 'Кара',
    pt: 'Karla',
  },
  '6_丙': {
    ja: 'アデル',
    en: 'Adele',
    zh: '阿黛爾',
    ko: '아델',
    es: 'Adel',
    fr: 'Adèle',
    de: 'Adel',
    ru: 'Адель',
    pt: 'Adele',
  },
  '6_丁': {
    ja: 'メルシー',
    en: 'Merci',
    zh: '梅爾西',
    ko: '멜시',
    es: 'Merci',
    fr: 'Mercy',
    de: 'Merci',
    ru: 'Мерси',
    pt: 'Merci',
  },
  '6_戊': {
    ja: 'ドンナ',
    en: 'Donna',
    zh: '唐娜',
    ko: '돈나',
    es: 'Donna',
    fr: 'Donna',
    de: 'Donna',
    ru: 'Донна',
    pt: 'Donna',
  },
  '6_己': {
    ja: 'エイド',
    en: 'Aid',
    zh: '艾德',
    ko: '에이드',
    es: 'Eido',
    fr: 'Aidé',
    de: 'Eido',
    ru: 'Эйд',
    pt: 'Eid',
  },
  '6_庚': {
    ja: 'アイマン',
    en: 'Aiman',
    zh: '艾曼',
    ko: '아이만',
    es: 'Aiman',
    fr: 'Aïman',
    de: 'Aiman',
    ru: 'Айман',
    pt: 'Aiman',
  },
  '6_辛': {
    ja: 'ベロア',
    en: 'Velour',
    zh: '貝羅亞',
    ko: '벨로아',
    es: 'Velour',
    fr: 'Velours',
    de: 'Velour',
    ru: 'Велора',
    pt: 'Velour',
  },
  '6_壬': {
    ja: 'ワッチ',
    en: 'Watch',
    zh: '瓦奇',
    ko: '와치',
    es: 'Watch',
    fr: 'Watch',
    de: 'Watsch',
    ru: 'Ватчи',
    pt: 'Wachi',
  },
  '6_癸': {
    ja: 'ダンテ',
    en: 'Dante',
    zh: '但丁',
    ko: '단테',
    es: 'Dante',
    fr: 'Dante',
    de: 'Dante',
    ru: 'Данте',
    pt: 'Dante',
  },
  '7_甲': {
    ja: 'パット',
    en: 'Pat',
    zh: '帕特',
    ko: '팟',
    es: 'Pat',
    fr: 'Patt',
    de: 'Pat',
    ru: 'Патт',
    pt: 'Pat',
  },
  '7_乙': {
    ja: 'チャーリー',
    en: 'Charlie',
    zh: '查理',
    ko: '차이리',
    es: 'Charlie',
    fr: 'Charlie',
    de: 'Charlie',
    ru: 'Чарли',
    pt: 'Charlie',
  },
  '7_丙': {
    ja: 'ミラ',
    en: 'Mira',
    zh: '米拉',
    ko: '미라',
    es: 'Mira',
    fr: 'Mira',
    de: 'Mira',
    ru: 'Мира',
    pt: 'Mira',
  },
  '7_丁': {
    ja: 'ステファニー',
    en: 'Stephanie',
    zh: '史黛芬妮',
    ko: '스테파니',
    es: 'Stefanny',
    fr: 'Stéphanie',
    de: 'Stephanie',
    ru: 'Стефани',
    pt: 'Stephanie',
  },
  '7_戊': {
    ja: 'クッキー',
    en: 'Cookie',
    zh: '餅乾',
    ko: '쿠키',
    es: 'Galleta',
    fr: 'Cookie',
    de: 'Cookie',
    ru: 'Печенье',
    pt: 'Biscoito',
  },
  '7_己': {
    ja: 'グミー',
    en: 'Gummy',
    zh: '果果',
    ko: '구미',
    es: 'Gummy',
    fr: 'Gummy',
    de: 'Gummy',
    ru: 'Гуми',
    pt: 'Gummy',
  },
  '7_庚': {
    ja: 'リック',
    en: 'Rick',
    zh: '利克',
    ko: '릭',
    es: 'Rick',
    fr: 'Rick',
    de: 'Rick',
    ru: 'Рик',
    pt: 'Rick',
  },
  '7_辛': {
    ja: 'マーガレット',
    en: 'Margaret',
    zh: '瑪格麗特',
    ko: '마가렛',
    es: 'Margarita',
    fr: 'Marguerite',
    de: 'Margaret',
    ru: 'Маргарета',
    pt: 'Margaret',
  },
  '7_壬': {
    ja: 'ペインター',
    en: 'Painter',
    zh: '畫家',
    ko: '페인터',
    es: 'Pintor',
    fr: 'Peintre',
    de: 'Maler',
    ru: 'Художник',
    pt: 'Pintor',
  },
  '7_癸': {
    ja: 'イーリア',
    en: 'Iria',
    zh: '伊莉雅',
    ko: '이리아',
    es: 'Iria',
    fr: 'Eliya',
    de: 'Iria',
    ru: 'Илия',
    pt: 'Iria',
  },
  '8_甲': {
    ja: 'ボタゴン',
    en: 'Botagon',
    zh: '波達公',
    ko: '보타곤',
    es: 'Botagón',
    fr: 'Botagon',
    de: 'Botagon',
    ru: 'Ботагон',
    pt: 'Botagon',
  },
  '8_乙': {
    ja: 'ミスト',
    en: 'Mist',
    zh: '霧霧',
    ko: '미스트',
    es: 'Mist',
    fr: 'Mist',
    de: 'Mist',
    ru: 'Мист',
    pt: 'Mist',
  },
  '8_丙': {
    ja: 'ブランドン',
    en: 'Brandon',
    zh: '布蘭登',
    ko: '브랜든',
    es: 'Brandon',
    fr: 'Brandon',
    de: 'Brandon',
    ru: 'Брэндон',
    pt: 'Brandon',
  },
  '8_丁': {
    ja: 'グーニー',
    en: 'Goonie',
    zh: '古尼',
    ko: '구니',
    es: 'Goonie',
    fr: 'Gouni',
    de: 'Güni',
    ru: 'Гуни',
    pt: 'Goony',
  },
  '8_戊': {
    ja: 'フラッフィー',
    en: 'Fluffy',
    zh: '毛毛球',
    ko: '플러피',
    es: 'Fluffy',
    fr: 'Fluffy',
    de: 'Fluffy',
    ru: 'Флаффи',
    pt: 'Fluffy',
  },
  '8_己': {
    ja: 'ウォル',
    en: 'Wal',
    zh: '沃爾',
    ko: '왈',
    es: 'Wal',
    fr: 'Wol',
    de: 'Wol',
    ru: 'Вол',
    pt: 'Wol',
  },
  '8_庚': {
    ja: 'グレース',
    en: 'Grace',
    zh: '格蕾絲',
    ko: '그레이스',
    es: 'Gracia',
    fr: 'Grace',
    de: 'Grace',
    ru: 'Грейс',
    pt: 'Grace',
  },
  '8_辛': {
    ja: 'メイソン',
    en: 'Mason',
    zh: '梅森',
    ko: '메이슨',
    es: 'Mason',
    fr: 'Mason',
    de: 'Mason',
    ru: 'Мэйсон',
    pt: 'Mason',
  },
  '8_壬': {
    ja: 'タジー',
    en: 'Taji',
    zh: '塔基',
    ko: '타지',
    es: 'Tajy',
    fr: 'Tajy',
    de: 'Taji',
    ru: 'Тадзи',
    pt: 'Taji',
  },
  '8_癸': {
    ja: 'ポコ',
    en: 'Poco',
    zh: '波可',
    ko: '포코',
    es: 'Poco',
    fr: 'Poko',
    de: 'Poko',
    ru: 'Поко',
    pt: 'Poko',
  },
  '9_甲': {
    ja: 'ヴェロニカ',
    en: 'Veronica',
    zh: '維羅妮卡',
    ko: '베로니카',
    es: 'Verónica',
    fr: 'Véronica',
    de: 'Veronika',
    ru: 'Вероника',
    pt: 'Verônica',
  },
  '9_乙': {
    ja: 'エレフ',
    en: 'Eleph',
    zh: '埃蕾夫',
    ko: '엘레프',
    es: 'Elef',
    fr: 'Elève',
    de: 'Elef',
    ru: 'Элеф',
    pt: 'Elef',
  },
  '9_丙': {
    ja: 'フィオナ',
    en: 'Fiona',
    zh: '菲奧娜',
    ko: '피오나',
    es: 'Fiona',
    fr: 'Fiona',
    de: 'Fiona',
    ru: 'Фиона',
    pt: 'Fiona',
  },
  '9_丁': {
    ja: 'ニコール',
    en: 'Nicole',
    zh: '妮可',
    ko: '니콜',
    es: 'Nicole',
    fr: 'Nicole',
    de: 'Nicole',
    ru: 'Николь',
    pt: 'Nicole',
  },
  '9_戊': {
    ja: 'バルモア',
    en: 'Balmore',
    zh: '巴爾莫爾',
    ko: '발모어',
    es: 'Balmor',
    fr: 'Balmor',
    de: 'Balmore',
    ru: 'Бальмор',
    pt: 'Balmore',
  },
  '9_己': {
    ja: 'シーザー',
    en: 'Caesar',
    zh: '西薩',
    ko: '시저',
    es: 'César',
    fr: 'César',
    de: 'Cäsar',
    ru: 'Цезарь',
    pt: 'César',
  },
  '9_庚': {
    ja: 'ピッカ',
    en: 'Pikka',
    zh: '皮卡',
    ko: '픽카',
    es: 'Pikka',
    fr: 'Pikka',
    de: 'Pikka',
    ru: 'Пикка',
    pt: 'Pikka',
  },
  '9_辛': {
    ja: 'ステラ',
    en: 'Stella',
    zh: '斯特拉',
    ko: '스텔라',
    es: 'Stella',
    fr: 'Stella',
    de: 'Stella',
    ru: 'Стелла',
    pt: 'Stela',
  },
  '9_壬': {
    ja: 'ミンク',
    en: 'Mink',
    zh: '敏克',
    ko: '밍크',
    es: 'Mink',
    fr: 'Mink',
    de: 'Mink',
    ru: 'Минк',
    pt: 'Mink',
  },
  '9_癸': {
    ja: 'ウーパ',
    en: 'Upa',
    zh: '烏巴',
    ko: '우파',
    es: 'Upa',
    fr: 'Oupa',
    de: 'Uppa',
    ru: 'Упа',
    pt: 'Uppa',
  },
};

export function getLocalizedCharacterName(id: string, lang: string = 'ja'): string {
  const cleanLang = lang.split('-')[0].toLowerCase();
  const names = CHARACTER_NAMES[id];
  if (names) {
    return names[cleanLang] || names['ja'];
  }
  const char = CHARACTER_MAP[id];
  return char ? char.name : id;
}
