export const CHARACTER_BASE_URL = 'https://kss-lp.vercel.app/characters/';

export const CHARACTER_MAP: Record<string, { name: string, file: string }> = {
  '1_甲': { name: 'アイス', file: '1_kou' },
  '1_乙': { name: 'タンブラー', file: '1_otsu' },
  '1_丙': { name: 'ピクス', file: '1_hei' },
  '1_丁': { name: 'カーク', file: '1_tei' },
  '1_戊': { name: 'ゴードン', file: '1_bo' },
  '1_己': { name: 'ポレフ', file: '1_ki' },
  '1_庚': { name: 'リンガー', file: '1_kou2' },
  '1_辛': { name: 'オルガ', file: '1_shin' },
  '1_壬': { name: 'アデュー', file: '1_jin' },
  '1_癸': { name: 'ウォルター', file: '1_ki2' },
  '2_甲': { name: 'ホーリー', file: '2_kou' },
  '2_乙': { name: 'エマ', file: '2_otsu' },
  '2_丙': { name: 'プーミー', file: '2_hei' },
  '2_丁': { name: 'コトン', file: '2_tei' },
  '2_戊': { name: 'タンタン', file: '2_bo' },
  '2_己': { name: 'ゴルトン', file: '2_ki' },
  '2_庚': { name: 'ダルリ', file: '2_kou2' },
  '2_辛': { name: 'ポポ', file: '2_shin' },
  '2_壬': { name: 'イース', file: '2_jin' },
  '2_癸': { name: 'リック', file: '2_ki2' },
  '3_甲': { name: 'テント', file: '3_kou' },
  '3_乙': { name: 'オリー', file: '3_otsu' },
  '3_丙': { name: 'レミー', file: '3_hei' },
  '3_丁': { name: 'ジャスパー', file: '3_tei' },
  '3_戊': { name: 'ムーチョ', file: '3_bo' },
  '3_己': { name: 'シケダ', file: '3_ki' },
  '3_庚': { name: 'マルファン', file: '3_kou2' },
  '3_辛': { name: 'リンク', file: '3_shin' },
  '3_壬': { name: 'バン', file: '3_jin' },
  '3_癸': { name: 'ユルグ', file: '3_ki2' },
  '4_甲': { name: 'ペイジー', file: '4_kou' },
  '4_乙': { name: 'ナーム', file: '4_otsu' },
  '4_丙': { name: 'サーシャ', file: '4_hei' },
  '4_丁': { name: 'アントニー', file: '4_tei' },
  '4_戊': { name: 'クラウディア', file: '4_bo' },
  '4_己': { name: 'ピット', file: '4_ki' },
  '4_庚': { name: 'ジャイロ', file: '4_kou2' },
  '4_辛': { name: 'ペスカ', file: '4_shin' },
  '4_壬': { name: 'シーグル', file: '4_jin' },
  '4_癸': { name: 'カカオ', file: '4_ki2' },
  '5_甲': { name: 'ファンタ', file: '5_kou' },
  '5_乙': { name: 'ヴァーナ', file: '5_otsu' },
  '5_丙': { name: 'ソラリ', file: '5_hei' },
  '5_丁': { name: 'シスコ', file: '5_tei' },
  '5_戊': { name: 'シャーロット', file: '5_bo' },
  '5_己': { name: 'ロジャー', file: '5_ki' },
  '5_庚': { name: 'ドミノ', file: '5_kou2' },
  '5_辛': { name: 'チップス', file: '5_shin' },
  '5_壬': { name: 'ペトン', file: '5_jin' },
  '5_癸': { name: 'アーナンダ', file: '5_ki2' },
  '6_甲': { name: 'モーリス', file: '6_kou' },
  '6_乙': { name: 'カーラ', file: '6_otsu' },
  '6_丙': { name: 'アデル', file: '6_hei' },
  '6_丁': { name: 'メルシー', file: '6_tei' },
  '6_戊': { name: 'ドンナ', file: '6_bo' },
  '6_己': { name: 'エイド', file: '6_ki' },
  '6_庚': { name: 'アイマン', file: '6_kou2' },
  '6_辛': { name: 'ベロア', file: '6_shin' },
  '6_壬': { name: 'ワッチ', file: '6_jin' },
  '6_癸': { name: 'ダンテ', file: '6_ki2' },
  '7_甲': { name: 'パット', file: '7_kou' },
  '7_乙': { name: 'マーガレット', file: '7_otsu' },
  '7_丙': { name: 'ミラ', file: '7_hei' },
  '7_丁': { name: 'ステファニー', file: '7_tei' },
  '7_戊': { name: 'クッキー', file: '7_bo' },
  '7_己': { name: 'グミー', file: '7_ki' },
  '7_庚': { name: 'アリアナ', file: '7_kou2' },
  '7_辛': { name: 'チャーリー', file: '7_shin' },
  '7_壬': { name: 'ペインター', file: '7_jin' },
  '7_癸': { name: 'イーリア', file: '7_ki2' },
  '8_甲': { name: 'ボタゴン', file: '8_kou' },
  '8_乙': { name: 'ミスト', file: '8_otsu' },
  '8_丙': { name: 'ブランドン', file: '8_hei' },
  '8_丁': { name: 'グーニー', file: '8_tei' },
  '8_戊': { name: 'フラッフィー', file: '8_bo' },
  '8_己': { name: 'ウォル', file: '8_ki' },
  '8_庚': { name: 'グレース', file: '8_kou2' },
  '8_辛': { name: 'メイソン', file: '8_shin' },
  '8_壬': { name: 'タジー', file: '8_jin' },
  '8_癸': { name: 'ポコ', file: '8_ki2' },
  '9_甲': { name: 'ヴェロニカ', file: '9_kou' },
  '9_乙': { name: 'エレフ', file: '9_otsu' },
  '9_丙': { name: 'フィオナ', file: '9_hei' },
  '9_丁': { name: 'ニコール', file: '9_tei' },
  '9_戊': { name: 'バルモア', file: '9_bo' },
  '9_己': { name: 'シーザー', file: '9_ki' },
  '9_庚': { name: 'ピッカ', file: '9_kou2' },
  '9_辛': { name: 'ステラ', file: '9_shin' },
  '9_壬': { name: 'ミンク', file: '9_jin' },
  '9_癸': { name: 'ウーパ', file: '9_ki2' },
};

export function getCharacterImageUrl(id: string): string {
  const char = CHARACTER_MAP[id];
  if (char) {
    return `${CHARACTER_BASE_URL}${char.file}.png`;
  }
  return '/hero.png'; // Fallback
}
